// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9QXzIrXC3akAlK9pnhDsZ9T6UHOHbGqY',
    appId: '1:77819801145:android:78213148cf2ea1dae8a7e8',
    messagingSenderId: '77819801145',
    projectId: 'knapsak-app-887fc',
    storageBucket: 'knapsak-app-887fc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQwVG-uGmNADFmid4ek79deoJoybGcgRk',
    appId: '1:77819801145:ios:10e37b45ca6df1ffe8a7e8',
    messagingSenderId: '77819801145',
    projectId: 'knapsak-app-887fc',
    storageBucket: 'knapsak-app-887fc.firebasestorage.app',
    iosBundleId: 'com.knapsak.knapsakFlutter',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC00IrM2gzA97hZZvt-ulnKE90SlmttIBs',
    appId: '1:77819801145:web:963773e36c2d7cb8e8a7e8',
    messagingSenderId: '77819801145',
    projectId: 'knapsak-app-887fc',
    authDomain: 'knapsak-app-887fc.firebaseapp.com',
    storageBucket: 'knapsak-app-887fc.firebasestorage.app',
    measurementId: 'G-LJV7SN2JTB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQwVG-uGmNADFmid4ek79deoJoybGcgRk',
    appId: '1:77819801145:ios:10e37b45ca6df1ffe8a7e8',
    messagingSenderId: '77819801145',
    projectId: 'knapsak-app-887fc',
    storageBucket: 'knapsak-app-887fc.firebasestorage.app',
    iosBundleId: 'com.knapsak.knapsakFlutter',
  );
}
